### ISSUE TITLE
Kilka monitorów

### ISSUE THREAD

**Issue by rafal366** [golabtomek/allkeeper#1]
![screenshot 7](https://cloud.githubusercontent.com/assets/1767169/23122252/c12b857c-f763-11e6-94e6-63839141993e.png)

W miejscu gdzie kończy się przeglądarka, kończy się ekran, i jak widać, aplikacja wyświetla się częściowo na lewym ekranie. Czasami wyświetla się poprawnie

**Comment by golabtomek** [comment]
Tak, wiem o tym ;) Obsługę wielu monitorów napiszę na pewno w najbliższym czasie.
Pracuję nad lepszym sposobem aktywacji okna - aktualnie to zwykłe przesunięcie, stąd te problemy. 
Dziwi mnie tylko fakt, że czasami jest poprawnie a czasami jest źle. Dam znać, jak rozwiąże problem! ;)

**Comment by golabtomek** [comment]
Jakbyś mógł sprawdzić teraz, to byłbym wdzięczny. Zaktualizowany zarówno kod jak i instalka w zip'ie.

**Comment by rafal366** [comment]
Jest o wiele lepiej, ale czasami jeszcze nachodzi na lewy ekran.

**Comment by golabtomek** [comment]
Przypisałem teraz pozycje bezpośrednio do parametrów głównego monitora. Aktualnie nic innego nie mogę zrobić, więc jeśli to nie zadziała, to będę musiał to inaczej rozwiązać.
Przy teście u mnie na dwóch monitorach (laptop+TV) nie zauważyłem takiego problemu. Jeśli teraz objawy nie ustąpią, to napisz jeszcze raz - oczywiście jeśli masz czas na sprawdzenie ;)

**Comment by rafal366** [comment]
W wersji 0.2 jest dobrze, tylko problem jest teraz taki, że okienko pokazuje się tylko za pierwszym razem, a później już tylko wysuwa się o 1-2 piksele

**Comment by golabtomek** [comment]
Może problem leżał w storyboardzie w XAML... Ustawiłem teraz szerokość i wysokość w ViewModelu, więc możesz spróbować ponownie ;) Dzięki za feedback!

**Comment by rafal366** [comment]
Teraz jest super :)
